const schedules = [
  // Example of live and completed games
  {
    teamA: 'Bills',
    teamB: 'Chiefs',
    startTime: '2025-01-20T18:00:00Z',
    endTime: '2025-01-20T21:00:00Z',
  },
  {
    teamA: 'Cowboys',
    teamB: '49ers',
    startTime: '2025-01-20T20:00:00Z',
    endTime: '2025-01-20T23:00:00Z',
  },
  // Placeholder for all other teams as "available"
  { teamA: 'Cardinals', teamB: null, startTime: null, endTime: null },
  { teamA: 'Falcons', teamB: null, startTime: null, endTime: null },
  { teamA: 'Ravens', teamB: null, startTime: null, endTime: null },
  { teamA: 'Panthers', teamB: null, startTime: null, endTime: null },
  { teamA: 'Bears', teamB: null, startTime: null, endTime: null },
  { teamA: 'Bengals', teamB: null, startTime: null, endTime: null },
  { teamA: 'Browns', teamB: null, startTime: null, endTime: null },
  { teamA: 'Broncos', teamB: null, startTime: null, endTime: null },
  { teamA: 'Lions', teamB: null, startTime: null, endTime: null },
  { teamA: 'Packers', teamB: null, startTime: null, endTime: null },
  { teamA: 'Texans', teamB: null, startTime: null, endTime: null },
  { teamA: 'Colts', teamB: null, startTime: null, endTime: null },
  { teamA: 'Jaguars', teamB: null, startTime: null, endTime: null },
  { teamA: 'Raiders', teamB: null, startTime: null, endTime: null },
  { teamA: 'Chargers', teamB: null, startTime: null, endTime: null },
  { teamA: 'Rams', teamB: null, startTime: null, endTime: null },
  { teamA: 'Dolphins', teamB: null, startTime: null, endTime: null },
  { teamA: 'Vikings', teamB: null, startTime: null, endTime: null },
  { teamA: 'Patriots', teamB: null, startTime: null, endTime: null },
  { teamA: 'Saints', teamB: null, startTime: null, endTime: null },
  { teamA: 'Giants', teamB: null, startTime: null, endTime: null },
  { teamA: 'Jets', teamB: null, startTime: null, endTime: null },
  { teamA: 'Eagles', teamB: null, startTime: null, endTime: null },
  { teamA: 'Steelers', teamB: null, startTime: null, endTime: null },
  { teamA: 'Seahawks', teamB: null, startTime: null, endTime: null },
  { teamA: 'Buccaneers', teamB: null, startTime: null, endTime: null },
  { teamA: 'Titans', teamB: null, startTime: null, endTime: null },
  { teamA: 'Commanders', teamB: null, startTime: null, endTime: null },
];

module.exports = schedules;
